### ISSUE TITLE
Client disconnect during authentication

### ISSUE THREAD

**Issue by WillAyd** [gtker/wow_vanilla_server#2]
Trying to get a client to connect I am running into this error:

```sh
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: MatchProofsError { client_proof: [130, 19, 212, 75, 207, 183, 62, 130, 224, 247, 206, 77, 153, 190, 58, 2, 245, 96, 206, 95], server_proof: [230, 175, 26, 215, 241, 151, 148, 252, 158, 135, 103, 137, 67, 131, 57, 37, 200, 12, 137, 241] }', src/auth.rs:272:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1090:23
   4: wow_vanilla_server::auth::login_version_3::{{closure}}
             at ./src/auth.rs:267:22
   5: wow_vanilla_server::auth::handle::{{closure}}
             at ./src/auth.rs:50:51
```

Which points to here: https://github.com/gtker/wow_vanilla_server/blob/645455c6a6e92fb11bc4b93c999e504dd52bafd0/src/auth.rs#L267

Trying to look through but relatively new to this - any pointers on what I should be checking? If it matters I am running this via wine on a platform that is little endian

**Comment by gtker** [comment]
Which credentials did you use?
The server accepts any username/password combo that is identical, so username `a` and password `a`.

**Comment by WillAyd** [comment]
Ah ok. I was just putting random input in and expecting a response back that the credentials were invalid instead of a panic/client disconnect. Assuming that still needs to be implemented

**Comment by gtker** [comment]
Ah, yeah, that'll do it.

This project is a lot more just basic scaffolding that I can change however I want to examine the client response and further develop `wow_messages`, so it doesn't really have things like error handling or config parsing. :)

I'm not really that interested in making this a "fully featured" server like mangos because of how insanely large of a goal that is. Instead I want to keep it as focused as possible on only showcasing the interactions with the client and using it for prototyping.
